
POST http://localhost:8080/reg
Content-Type: application/json

{
  "login": "yuliya@gmail.com",
  "password": "123"
}

###

POST http://localhost:8080/auth
Content-Type: application/json

{
  "login": "yuliya@gmail.com",
  "password": "123"
}