
POST http://localhost:8080/reg
Content-Type: application/json

{
  "login": "aaa@gmail.com",
  "password": "123",
  "name": "aaa"
}

###

POST http://localhost:8080/auth
Content-Type: application/json

{
  "login": "aaa@gmail.com",
  "password": "123",
  "name": "aaa"
}

###

GET http://localhost:8080/test/t/t/t

###
GET http://localhost:8080/users/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibG9naW4iOiJ5dWxpeWFAZ21haWwuY29tIiwicm9sZSI6IlVTRVIifQ.HtFrD0yzRgiqc-_WhCjNl-mC-xXfqKwIhcieScIjuqw